version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: hw11
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"